name: Build isabelle session

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  isabelle-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: chache output
        id: cache-output
        uses: actions/cache@v4
        with:
          path: ./out
          key: ${{ runner.os }}-out

      - name: Isabelle
        uses: 'docker://hllm/isabelle-docker'
        with:
          entrypoint: /bin/bash
          args: build.sh -c
