name: Check Isabelle for PRs

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read

jobs:
  isabelle-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3.4.0

      - name: chache output
        id: cache-output
        uses: actions/cache@v3
        with:
          path: ./out
          key: ${{ runner.os }}-out

      - name: Isabelle-action
        uses: TheHllm/isabelle-action@v1.10
        with:
          session: LinearTimeBranchingTimeSpectroscopyAccountingForSilentSteps
      
      - uses: actions/upload-artifact@v3
        with:
          name: document
          path: ./out/AFP/LinearTimeBranchingTimeSpectroscopyAccountingForSilentSteps/document.pdf
          