name: Build isabelle session

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  isabelle-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3.4.0

      - name: Isabelle
        uses: 'docker://hllm/isabelle-docker'
        with:
          entrypoint: /bin/bash
          args: build.sh -c
