name: Build Isabelle

on:
  push:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read

jobs:
  isabelle-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3.4.0

      - name: chache output
        id: cache-output
        uses: actions/cache@v3
        with:
          path: ./out
          key: ${{ runner.os }}-out

      - name: Isabelle-action
        uses: TheHllm/isabelle-action@v1.9
        with:
          session: LinearTimeBranchingTimeSpectroscopyAccountingForSilentSteps
      
      - uses: actions/upload-artifact@v3
        with:
          name: document
          path: ./out/AFP/LinearTimeBranchingTimeSpectroscopyAccountingForSilentSteps/document.pdf

      - uses: actions/upload-artifact@v3
        with:
          name: outline
          path: ./out/AFP/LinearTimeBranchingTimeSpectroscopyAccountingForSilentSteps/outline.pdf

      - uses: actions/upload-artifact@v3
        with:
          name: out
          path: ./out