name: Build Isabelle

on:
  push:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read

jobs:
  isabelle-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Isabelle-action
        uses: benkeks/isabelle-action@v1.7
        with:
          session: LinearTimeBranchingTimeSpectroscopyAccountingForSilentSteps
      
      - uses: actions/upload-artifact@v3
        with:
          name: document
          path: ./out/*/*/document.pdf

      - uses: actions/upload-artifact@v3
        with:
          name: out
          path: ./out