name: Check and deploy Isabelle theory

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  isabelle-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: chache output
        id: cache-output
        uses: actions/cache@v4
        with:
          path: ./out
          key: ${{ runner.os }}-out

      - name: Isabelle
        uses: 'docker://hllm/isabelle-docker'
        with:
          entrypoint: /bin/bash
          args: >
            -c "/home/isabelle/Isabelle/bin/isabelle build
            -v
            -o document=pdf
            -o document_variants=document:outline=/proof,/ML
            -P out
            -d .
            Weak_Spectroscopy"
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Copy documentation
        run: "cp -r ./out/ ./_site/"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: isabelle-build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
